### ISSUE TITLE
博客别人也可以写

### ISSUE THREAD

**Issue by chenxuhua** [lifesinger/lifesinger.github.io#225]
This just a test

**Comment by flyyang** [comment]
近1000watch就为了看你一个test?

**Comment by chenxuhua** [comment]
抱歉，抱歉！听说issue博客内容任何人都可发表，就做了个测试，没想到真的是这样。影响了大家的阅读，深感抱歉！！

**Comment by zhangjh** [comment]
真是要取消watch了，邮箱被各种提醒塞满了
